#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Ayaka Murakoshi
# SPDX-Linense-Identifier: BSD-3-Clause

import sys

ans = 0
for line in sys.stdin:
    try:
         ans -= int(line)
    except:
         ans -= float(line)
print(ans)

# このソフトウェアパッケージは、3条項BSDライセンスの下、再頒布および使用が許可されます.
# © 2023 Ayaka Murakoshi
